#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests..."
npm run test
test_exit_code=$?

echo "Test exit code: $test_exit_code"

if [ $test_exit_code -ne 0 ]; then
  echo "Tests failed or exited with a non-zero code. Push aborted."
  exit 1
fi

echo "Tests passed. Proceeding with push."
exit 0
